// MODULES WHOSE CAPACITOR BEHAVIOUR DEPENDS ON CARRYING CHARGES.
//
// GENERATED by scripts/build-ancillary.mjs from CCP's own group table:
//   76 Capacitor Booster
//   1156 Ancillary Shield Booster
//   1199 Ancillary Armor Repairer
//   1697 Ancillary Remote Shield Booster
//   1698 Ancillary Remote Armor Repairer
//
// BY GROUP, NEVER BY NAME. "Ancillary Current Router" is a RIG — a name match
// would have treated it as an unloaded ancillary module and suppressed a
// genuine capacitor problem.
//
// WHY THIS EXISTS: an Ancillary Shield Booster with no charges drains
// capacitor that a charged one would not touch, and a Capacitor Booster with
// no charges injects nothing. Judging capacitor from an unloaded fit measures
// the loadout, not the fit — so when any of these is empty, the app declines
// to call capacitor broken.
//
// Public EVE data: nothing here is player-specific.

const ANCILLARY = new Set<number>([
  577,
  2024,
  3556,
  3558,
  3566,
  3568,
  3576,
  3578,
  4391,
  4829,
  4831,
  4833,
  4835,
  4955,
  4957,
  4959,
  4961,
  5007,
  5009,
  5011,
  5013,
  5017,
  5047,
  5049,
  5051,
  5053,
  14172,
  14174,
  14176,
  14178,
  14180,
  14182,
  14184,
  14186,
  15128,
  15130,
  15132,
  15134,
  15136,
  15138,
  15140,
  15142,
  15772,
  15774,
  15776,
  15778,
  15780,
  15782,
  15784,
  15786,
  20555,
  20557,
  20559,
  23807,
  23809,
  23811,
  32772,
  32774,
  32780,
  33076,
  33101,
  33103,
  41476,
  41477,
  41478,
  41479,
  41480,
  41481,
  41482,
  41483,
  41491,
  41492,
  41493,
  41494,
  41495,
  41503,
  41504,
  47836,
  47838,
  47840,
  47842,
  47844,
  47846,
  56308,
  56310,
  85027,
  85028,
  88713,
  88714,
  88715,
  88716,
  88717,
  88718,
  88719,
  88720,
  88721,
]);

/** true when this module only behaves itself with charges loaded */
export const isAncillary = (typeId: number): boolean => ANCILLARY.has(typeId);

export const ANCILLARY_COUNT = ANCILLARY.size;
