// PI STRUCTURE TYPES -> their role on a planet.
//
// GENERATED by scripts/build-pitypes.mjs from the bundled CCP type table
// (groups 1027, 1028, 1029, 1030, 1063). It is a static table rather than a
// runtime lookup because typedb.json only carries an inventory group for
// SHIPS, and classifying a pin by name would break the moment CCP ships a
// new planet type.
//
// Public EVE data: nothing here is player-specific.

export type PinRole = 'command' | 'factory' | 'storage' | 'launchpad' | 'extractor';

const TABLE = new Map<number, PinRole>([
  [2129, 'command'],  // Limited Barren Command Center
  [2130, 'command'],  // Standard Barren Command Center
  [2131, 'command'],  // Improved Barren Command Center
  [2132, 'command'],  // Advanced Barren Command Center
  [2133, 'command'],  // Elite Barren Command Center
  [2134, 'command'],  // Limited Gas Command Center
  [2135, 'command'],  // Standard Gas Command Center
  [2136, 'command'],  // Improved Gas Command Center
  [2137, 'command'],  // Advanced Gas Command Center
  [2138, 'command'],  // Elite Gas Command Center
  [2139, 'command'],  // Limited Ice Command Center
  [2140, 'command'],  // Standard Ice Command Center
  [2141, 'command'],  // Improved Ice Command Center
  [2142, 'command'],  // Advanced Ice Command Center
  [2143, 'command'],  // Elite Ice Command Center
  [2144, 'command'],  // Limited Lava Command Center
  [2145, 'command'],  // Standard Lava Command Center
  [2146, 'command'],  // Improved Lava Command Center
  [2147, 'command'],  // Advanced Lava Command Center
  [2148, 'command'],  // Elite Lava Command Center
  [2149, 'command'],  // Limited Oceanic Command Center
  [2150, 'command'],  // Standard Oceanic Command Center
  [2151, 'command'],  // Improved Oceanic Command Center
  [2152, 'command'],  // Advanced Oceanic Command Center
  [2153, 'command'],  // Elite Oceanic Command Center
  [2154, 'command'],  // Limited Plasma Command Center
  [2155, 'command'],  // Standard Plasma Command Center
  [2156, 'command'],  // Improved Plasma Command Center
  [2157, 'command'],  // Advanced Plasma Command Center
  [2158, 'command'],  // Elite Plasma Command Center
  [2159, 'command'],  // Limited Storm Command Center
  [2160, 'command'],  // Standard Storm Command Center
  [2254, 'command'],  // Temperate Command Center
  [2256, 'launchpad'],  // Temperate Launchpad
  [2257, 'storage'],  // Ice Storage Facility
  [2469, 'factory'],  // Lava Basic Industry Facility
  [2470, 'factory'],  // Lava Advanced Industry Facility
  [2471, 'factory'],  // Plasma Basic Industry Facility
  [2472, 'factory'],  // Plasma Advanced Industry Facility
  [2473, 'factory'],  // Barren Basic Industry Facility
  [2474, 'factory'],  // Barren Advanced Industry Facility
  [2475, 'factory'],  // Barren High-Tech Production Plant
  [2480, 'factory'],  // Temperate Advanced Industry Facility
  [2481, 'factory'],  // Temperate Basic Industry Facility
  [2482, 'factory'],  // Temperate High-Tech Production Plant
  [2483, 'factory'],  // Storm Basic Industry Facility
  [2484, 'factory'],  // Storm Advanced Industry Facility
  [2485, 'factory'],  // Oceanic Advanced Industry Facility
  [2490, 'factory'],  // Oceanic Basic Industry Facility
  [2491, 'factory'],  // Ice Advanced Industry Facility
  [2492, 'factory'],  // Gas Basic Industry Facility
  [2493, 'factory'],  // Ice Basic Industry Facility
  [2494, 'factory'],  // Gas Advanced Industry Facility
  [2524, 'command'],  // Barren Command Center
  [2525, 'command'],  // Oceanic Command Center
  [2533, 'command'],  // Ice Command Center
  [2534, 'command'],  // Gas Command Center
  [2535, 'storage'],  // Oceanic Storage Facility
  [2536, 'storage'],  // Gas Storage Facility
  [2541, 'storage'],  // Barren Storage Facility
  [2542, 'launchpad'],  // Oceanic Launchpad
  [2543, 'launchpad'],  // Gas Launchpad
  [2544, 'launchpad'],  // Barren Launchpad
  [2549, 'command'],  // Lava Command Center
  [2550, 'command'],  // Storm Command Center
  [2551, 'command'],  // Plasma Command Center
  [2552, 'launchpad'],  // Ice Launchpad
  [2555, 'launchpad'],  // Lava Launchpad
  [2556, 'launchpad'],  // Plasma Launchpad
  [2557, 'launchpad'],  // Storm Launchpad
  [2558, 'storage'],  // Lava Storage Facility
  [2560, 'storage'],  // Plasma Storage Facility
  [2561, 'storage'],  // Storm Storage Facility
  [2562, 'storage'],  // Temperate Storage Facility
  [2574, 'command'],  // Improved Storm Command Center
  [2576, 'command'],  // Advanced Storm Command Center
  [2577, 'command'],  // Elite Storm Command Center
  [2578, 'command'],  // Limited Temperate Command Center
  [2581, 'command'],  // Standard Temperate Command Center
  [2582, 'command'],  // Improved Temperate Command Center
  [2585, 'command'],  // Advanced Temperate Command Center
  [2586, 'command'],  // Elite Temperate Command Center
  [2848, 'extractor'],  // Barren Extractor Control Unit
  [3060, 'extractor'],  // Gas Extractor Control Unit
  [3061, 'extractor'],  // Ice Extractor Control Unit
  [3062, 'extractor'],  // Lava Extractor Control Unit
  [3063, 'extractor'],  // Oceanic Extractor Control Unit
  [3064, 'extractor'],  // Plasma Extractor Control Unit
  [3067, 'extractor'],  // Storm Extractor Control Unit
  [3068, 'extractor'],  // Temperate Extractor Control Unit
]);

/** what this pin type does on a planet; null when it is not a PI structure */
export const pinRole = (typeId: number): PinRole | null => TABLE.get(typeId) ?? null;

/** roles whose capacity limits the planet — what "full" is measured against */
export const STORAGE_ROLES = new Set<PinRole>(['command', 'storage', 'launchpad']);

export const PI_TYPE_COUNT = TABLE.size;
