// SKILL RELEVANCE ENGINE — which skills matter for a ship fit or a topic,
// and why. Built on src/data/skilldb.json (generated by build-skilldb.mjs
// from CCP's SDE): per-type required skills, per-skill ship trait bonuses,
// and the dogma modifierInfo graph ("skill S modifies attribute A on items
// requiring skill R / in group G / on the ship / character-wide").
//
// HONEST LIMIT: this tells you WHICH skills touch a fit and WHAT they touch
// — it does not simulate stacked magnitudes (that's a fitting tool's job).
import raw from '../data/skilldb.json';
import { findByName, getType } from './typedb';

// ---- data ----
type SkillRow = [number, string, string, number, [number, number][], string];
type ModRow = [number, [number, number, number][]]; // skillId, [kind, attrId, extra][]
type TraitRow = [number, [number, number, number, string][]]; // shipId, [skillId|-1, bonus, unitId, text][]

const db = raw as unknown as {
  skills: SkillRow[];
  req: [number, [number, number][]][];
  g: [number, number][];
  gcat: [number, number][];
  traits: TraitRow[];
  mods: ModRow[];
  attrs: [number, string, number][];
  /** published fittables the market typedb can't resolve (abyssal bases,
   * civilian modules, boosters): [typeId, name] */
  extra: [number, string][];
};

export interface Skill {
  id: number;
  name: string;
  group: string;
  rank: number;
  prereqs: [number, number][];
  desc: string;
}

/** CUMULATIVE skill points at a level: 250 · rank · √32^(level−1) —
 * verified against EVE's published rank-1 table (250 / 1,414 / 8,000 /
 * 45,255 / 256,000) at every level. rank = the skill's training-time
 * multiplier, already in the bundled skilldb. */
export const spAtLevel = (rank: number, level: number): number =>
  level <= 0 ? 0 : Math.round(250 * rank * Math.pow(Math.sqrt(32), level - 1));

/** SP still to train from a CURRENT level to a target. The skills map only
 * stores whole levels, so partial progress into the next level is unknown
 * and counted as zero — the figure is the honest ceiling. */
export const spMissing = (rank: number, current: number, target: number): number =>
  Math.max(0, spAtLevel(rank, target) - spAtLevel(rank, current));

/** "45.3k" / "1.28M" — SP totals get big fast */
export const spShort = (n: number): string =>
  n >= 1e6 ? `${(n / 1e6).toFixed(2)}M` : n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);

export const allSkills: Skill[] = db.skills.map(([id, name, group, rank, prereqs, desc]) => ({
  id, name, group, rank, prereqs, desc,
}));
const skillById = new Map(allSkills.map((s) => [s.id, s]));
const reqByType = new Map(db.req);
const groupOfType = new Map(db.g);
const categoryOfGroup = new Map(db.gcat);
const traitsByShip = new Map(db.traits.map(([id, rows]) => [id, rows]));
const modsBySkill = new Map(db.mods.map(([id, rows]) => [id, rows]));
const attrName = new Map(db.attrs.map(([id, name]) => [id, name]));
const attrHasDisplay = new Map(db.attrs.map(([id, , hasDisp]) => [id, hasDisp === 1]));
const extraByName = new Map(db.extra.map(([id, name]) => [name.toLowerCase(), { id, name }]));
const extraNameById = new Map(db.extra.map(([id, name]) => [id, name]));

/** CHARGES (8) and DRONES (18) are "owned" items in dogma — owner-required
 * skill modifiers apply to them, not to fitted modules */
const isOwnedCategory = (typeId: number): boolean => {
  const cat = categoryOfGroup.get(groupOfType.get(typeId) ?? -1);
  return cat === 8 || cat === 18;
};

/** internal-only attributes (no CCP display name) worth showing anyway —
 * these are real player-facing effects, named here in English */
const INTERNAL_ATTR_LABELS: Record<string, string> = {
  maxActiveDrones: 'max active drones',
  warpCapacitorNeed: 'warp capacitor need',
  advancedAgility: 'agility (advanced hulls)',
  advancedCapitalAgility: 'agility (capital hulls)',
  moduleRepairRate: 'nanite repair rate',
};

export const skillInfo = (id: number): Skill | undefined => skillById.get(id);

/** dogma attribute ids this skill modifies (from the SDE's own modifier
 * rows) — used to shortlist which skills could possibly move a given
 * fitting resource before spending an engine run on each */
export const skillModAttrs = (id: number): number[] =>
  (modsBySkill.get(id) ?? []).map(([, attrId]) => attrId);
/** the skills a type DIRECTLY requires, [skillId, level] */
export const requiredSkillsOf = (typeId: number): [number, number][] => reqByType.get(typeId) ?? [];

// ---- attribute metadata (the fitting-window attributes panel) ----
type AttrDefRow = [number, string, number, number, number, number, number?];
const attrDefs = new Map(
  ((db as unknown as { attrsAll?: AttrDefRow[] }).attrsAll ?? []).map(([id, name, unitId, catId, published, highIsGood, hasDisplayName]) => [
    id,
    {
      id, name, unitId, catId,
      published: published === 1,
      highIsGood: highIsGood === 1,
      hasDisplayName: hasDisplayName === 1,
    },
  ]),
);
const unitNames = new Map((db as unknown as { units?: [number, string][] }).units ?? []);
const attrCatNames = new Map((db as unknown as { attrCats?: [number, string][] }).attrCats ?? []);

export interface AttrDef {
  id: number;
  name: string;
  unitId: number;
  catId: number;
  published: boolean;
  highIsGood: boolean;
  /** CCP gave it a real in-game display name (vs a raw internal name) */
  hasDisplayName: boolean;
}

export const attrDef = (id: number): AttrDef | undefined => attrDefs.get(id);
/** SDE meta groups: [id, "Tech II"], … — the module browser's variant tiers */
export const metaGroupNames = (): [number, string][] =>
  (db as unknown as { metaGroups?: [number, string][] }).metaGroups ?? [];

export interface ShipTrait {
  /** the skill the bonus scales with; -1 = role bonus */
  skillId: number;
  skillName: string;
  text: string;
  bonus: number;
  isPercent: boolean;
}

/** the hull's TRAITS — the in-game info window's bonus list */
export function shipTraits(hullId: number): ShipTrait[] {
  return (traitsByShip.get(hullId) ?? []).map(([skillId, bonus, unitId, text]) => ({
    skillId,
    skillName: skillId > 0 ? skillById.get(skillId)?.name ?? `#${skillId}` : 'Role bonus',
    text,
    bonus,
    isPercent: unitId === 105,
  }));
}
export const attrUnit = (unitId: number): string => unitNames.get(unitId) ?? '';
export const attrCategory = (catId: number): string => attrCatNames.get(catId) ?? 'Other';

/** EVE's unit CONVERSIONS — the raw dogma number is not what the game
 * shows. 108 inverse-absolute-% stores a resonance (0.4 → "60%" resist),
 * 127 absolute-% is a fraction, 105/109/111/124 modifier-% are multipliers
 * around 1 (1.05 → "+5%"). Verified against eveUnits + a live engine run. */
export function formatAttrValue(value: number, unitId: number): string {
  const round = (n: number) => (Math.abs(n) >= 1000 ? n.toFixed(0) : Math.abs(n) >= 10 ? n.toFixed(1) : n.toFixed(2));
  switch (unitId) {
    case 108: // inverse absolute percent (resonances)
      return `${round((1 - value) * 100)} %`;
    case 127: // absolute percent
      return `${round(value * 100)} %`;
    case 105:
    case 109:
    case 111:
    case 124: // modifier percent (multiplier around 1)
      return `${value >= 1 ? '+' : ''}${round((value - 1) * 100)} %`;
    default: {
      const unit = unitNames.get(unitId) ?? '';
      return `${round(value)}${unit ? ` ${unit}` : ''}`;
    }
  }
}
/** name of a published fittable the market typedb can't resolve (abyssal
 * bases, civilian modules, boosters) — for serializing owned fits */
export const extraTypeName = (id: number): string | undefined => extraNameById.get(id);
export const skillGroups: string[] = [...new Set(allSkills.map((s) => s.group))].sort();

// ---- EFT fit parsing ----

export interface FitItem {
  typeId: number;
  name: string;
  qty: number;
  /** charges loaded into this module stack, ONE ENTRY PER LOADED COPY
   * (parsed from "Module, Charge" lines — split ammo across a stack keeps
   * each copy's own charge; copies beyond this list are unloaded). The
   * charges ALSO appear as their own FitItems; this pairing is for the
   * dogma engine, which wants charges attached to their module. */
  charges: number[];
  /** how many copies of this stack are fitted OFFLINE (EFT "/OFFLINE") —
   * offline modules use no CPU/PG/cap and must not be simulated Active */
  offlineQty: number;
}

export interface ParsedFit {
  shipId: number | null;
  shipName: string;
  fitName: string;
  items: FitItem[]; // modules + charges + drones/cargo, hull EXCLUDED
  unresolved: string[];
  /** additional [Hull, name] headers found after the first fit — parsing
   * STOPS there rather than silently merging two fits into one analysis */
  extraFits: number;
}

/**
 * Parse the EVE client's "Copy to Clipboard" fit format (EFT):
 *   [Hull, fit name]
 *   Module Name
 *   Module Name, Charge Name
 *   [Empty Med slot]
 *   Drone Name x5
 * Unresolvable lines are REPORTED, never silently dropped.
 */
export function parseFit(text: string): ParsedFit {
  const out: ParsedFit = { shipId: null, shipName: '', fitName: '', items: [], unresolved: [], extraFits: 0 };
  const counts = new Map<number, FitItem>();
  const resolve = (name: string): { id: number; name: string } | undefined => {
    // "/OFFLINE" can trail the MODULE segment mid-line ("Launcher /OFFLINE,
    // Charge") as well as the whole line — strip it wherever it lands
    const clean = name.replace(/\s*\/offline$/i, '').trim();
    const t = findByName(clean);
    if (t) return { id: t.id, name: t.name };
    // abyssal/mutated bases, civilian modules, boosters: not on the market
    // (absent from typedb) but their skill requirements are real
    return extraByName.get(clean.toLowerCase());
  };
  const addItem = (name: string, qty: number, offline = false): boolean => {
    const t = resolve(name);
    if (!t) return false;
    const cur = counts.get(t.id);
    if (cur) {
      cur.qty += qty;
      if (offline) cur.offlineQty += qty;
    } else {
      counts.set(t.id, { typeId: t.id, name: t.name, qty, charges: [], offlineQty: offline ? qty : 0 });
    }
    return true;
  };
  let headerDone = false;
  for (const rawLine of text.split(/\r?\n/)) {
    // "/OFFLINE" marks a module fitted but offline (pyfa emits it, the EVE
    // client accepts it) — the module is still on the ship, skills and all,
    // but it draws no CPU/PG/cap, so the flag must survive into the item
    const isOffline = /\/offline\b/i.test(rawLine);
    const line = rawLine.trim().replace(/\s*\/offline$/i, '');
    if (!line) continue;
    if (headerDone && line.startsWith('[') && line.endsWith(']') && !/^\[empty .* slot\]$/i.test(line)) {
      // a SECOND fit header: analyzing a merged pile of two fits would lie
      // about both — stop here and say so
      out.extraFits += 1;
      break;
    }
    if (!headerDone && line.startsWith('[') && line.endsWith(']')) {
      headerDone = true;
      const inner = line.slice(1, -1);
      const comma = inner.indexOf(',');
      const hullName = (comma === -1 ? inner : inner.slice(0, comma)).trim();
      out.fitName = comma === -1 ? '' : inner.slice(comma + 1).trim();
      const hull = findByName(hullName);
      if (hull) {
        out.shipId = hull.id;
        out.shipName = hull.name;
      } else {
        out.shipName = hullName;
        out.unresolved.push(`${hullName} (hull)`);
      }
      continue;
    }
    if (/^\[empty .* slot\]$/i.test(line)) continue;
    // "Module, Charge" — try the full line first (some names contain commas)
    if (addItem(line.replace(/\s+x\d+$/i, ''), 1, isOffline)) {
      const m = line.match(/\s+x(\d+)$/i);
      if (m) {
        // re-add with the real quantity (addItem above put qty 1)
        const t = resolve(line.replace(/\s+x\d+$/i, ''))!;
        const entry = counts.get(t.id)!;
        entry.qty += Number(m[1]) - 1;
        if (isOffline) entry.offlineQty += Number(m[1]) - 1;
      }
      continue;
    }
    const comma = line.lastIndexOf(',');
    if (comma !== -1) {
      const mod = line.slice(0, comma).trim();
      const charge = line.slice(comma + 1).trim();
      const okMod = addItem(mod, 1, isOffline);
      const okCharge = addItem(charge, 1);
      if (okMod || okCharge) {
        if (!okMod) out.unresolved.push(mod);
        if (!okCharge) out.unresolved.push(charge);
        if (okMod && okCharge) {
          // one entry per LOADED COPY — split ammo across a stack keeps
          // each copy's own charge
          counts.get(resolve(mod)!.id)!.charges.push(resolve(charge)!.id);
        }
        continue;
      }
    }
    const qtyMatch = line.match(/^(.*?)\s+x(\d+)$/i);
    if (qtyMatch && addItem(qtyMatch[1].trim(), Number(qtyMatch[2]), isOffline)) continue;
    out.unresolved.push(line);
  }
  out.items = [...counts.values()];
  return out;
}

// ---- relevance ----

export type RelevanceTier = 1 | 2 | 3 | 4;
export const TIER_LABEL: Record<RelevanceTier, string> = {
  1: 'required',
  2: 'hull bonus',
  3: 'boosts this fit',
  4: 'fit-wide',
};

export interface SkillRelevance {
  skill: Skill;
  tier: RelevanceTier;
  /** highest level any fit item demands (incl. prerequisite chains) */
  requiredLevel: number;
  /** item names that demand it (or 'prerequisite of X') */
  requiredBy: string[];
  /** human strings: trait bonuses + dogma-modifier effects */
  boosts: string[];
}

const nameOfType = (id: number): string =>
  getType(id)?.name ?? extraNameById.get(id) ?? `#${id}`;

/** every skill relevant to the fit, tiered and explained.
 * fitAttrs = the set of dogma attribute ids present ANYWHERE in the fit
 * (hull + fitted items, from the ESF data bundle). With it, ship/char-wide
 * modifiers only count when the fit actually HAS the attribute they modify —
 * without it (data unavailable) the old, over-inclusive behavior applies:
 * Jump Drive Calibration is not relevant to a ship with no jump drive, and
 * Diplomacy's standings are not part of any fit. */
export function relevantForFit(fit: ParsedFit, attrsByType?: Map<number, Set<number>>): SkillRelevance[] {
  // union across the fit, for ship/char-wide (kind 0/1) checks
  const fitAttrs = attrsByType
    ? new Set([...attrsByType.values()].flatMap((s) => [...s]))
    : undefined;
  /** does THIS item carry the modified attribute? Cross-racial subsystem
   * skills share one dogma group (958 Core Subsystem etc.) and differ only
   * by which subsystemBonus… attribute they write — a Loki must not be
   * told to train Caldari Core Systems. No attr data = keep (inclusive). */
  const itemHasAttr = (typeId: number, attrId: number): boolean =>
    attrsByType ? (attrsByType.get(typeId)?.has(attrId) ?? false) : true;
  const map = new Map<number, SkillRelevance>();
  const touch = (skillId: number): SkillRelevance | undefined => {
    const skill = skillById.get(skillId);
    if (!skill) return undefined;
    let e = map.get(skillId);
    if (!e) {
      e = { skill, tier: 4, requiredLevel: 0, requiredBy: [], boosts: [] };
      map.set(skillId, e);
    }
    return e;
  };

  const fitTypeIds = [...(fit.shipId !== null ? [fit.shipId] : []), ...fit.items.map((i) => i.typeId)];

  // 1. required skills (direct + full prerequisite closure)
  const needed = new Map<number, { level: number; by: Set<string> }>();
  const demand = (skillId: number, level: number, by: string) => {
    const cur = needed.get(skillId);
    if (cur) {
      cur.level = Math.max(cur.level, level);
      cur.by.add(by);
    } else {
      needed.set(skillId, { level, by: new Set([by]) });
    }
    // prerequisites of the skill itself
    for (const [preId, preLvl] of skillById.get(skillId)?.prereqs ?? []) {
      const pre = needed.get(preId);
      const label = `prerequisite of ${skillById.get(skillId)?.name ?? '?'}`;
      if (!pre) demand(preId, preLvl, label);
      else if (preLvl > pre.level) {
        pre.level = preLvl;
        pre.by.add(label);
      } else pre.by.add(label);
    }
  };
  for (const tid of fitTypeIds) {
    for (const [skillId, level] of reqByType.get(tid) ?? []) demand(skillId, level, nameOfType(tid));
  }
  for (const [skillId, info] of needed) {
    const e = touch(skillId);
    if (!e) continue;
    e.tier = 1;
    e.requiredLevel = info.level;
    e.requiredBy = [...info.by];
  }

  // 2. hull trait bonuses (per-skill rows on the ship)
  if (fit.shipId !== null) {
    for (const [skillId, bonus, unitId, text] of traitsByShip.get(fit.shipId) ?? []) {
      if (skillId <= 0) continue; // role bonus — no skill involved
      const e = touch(skillId);
      if (!e) continue;
      if (e.tier > 2) e.tier = 2;
      const amount = bonus !== 0 ? `${bonus}${unitId === 105 ? '%' : ''} ` : '';
      e.boosts.push(`${fit.shipName}: ${amount}${text} (per level)`);
    }
  }

  // 3+4. dogma modifiers: which skills touch these items / the ship / everything
  const directReqOf = (tid: number): [number, number][] => reqByType.get(tid) ?? [];
  for (const [skillId, mods] of modsBySkill) {
    for (const [kind, attrId, extra] of mods) {
      const what = attrName.get(attrId) ?? `attr ${attrId}`;
      if (kind === 2 || kind === 5) {
        // kind 2 (location-required, domain shipID) hits items IN THE SHIP —
        // modules/rigs/subsystems, NEVER drones: a drone in space is not in
        // the ship, which is exactly why CCP writes every intended drone
        // bonus through the owner path instead. Verified against the shipped
        // SDE (2026-08-26): Signal Dispersion = LocationRequiredSkill/shipID
        // keyed on Electronic Warfare, which EC-300s happen to REQUIRE — the
        // old pool (!isCharge) kept drones in and told the user to train
        // Signal Dispersion "for EC drones", a bonus the game never applies.
        // kind 5 (owner-required, domain charID) hits OWNED items — charges,
        // drones. Citing a launcher for a charge boost was finding #5.
        const pool = fit.items.filter((i) => (kind === 5 ? isOwnedCategory(i.typeId) : !isOwnedCategory(i.typeId)));
        const hit = pool.filter((i) => directReqOf(i.typeId).some(([s]) => s === extra) && itemHasAttr(i.typeId, attrId));
        if (hit.length > 0) {
          const e = touch(skillId);
          if (!e) continue;
          if (e.tier > 3) e.tier = 3;
          e.boosts.push(`${what} — ${hit.slice(0, 3).map((h) => h.name).join(', ')}${hit.length > 3 ? ` +${hit.length - 3} more` : ''}`);
        }
      } else if (kind === 3) {
        const hit = fit.items.filter((i) => groupOfType.get(i.typeId) === extra && itemHasAttr(i.typeId, attrId));
        if (hit.length > 0) {
          const e = touch(skillId);
          if (!e) continue;
          if (e.tier > 3) e.tier = 3;
          e.boosts.push(`${what} — ${hit.slice(0, 3).map((h) => h.name).join(', ')}${hit.length > 3 ? ` +${hit.length - 3} more` : ''}`);
        }
      } else if (kind === 0 || kind === 1) {
        // attributes WITHOUT a CCP display name are the plumbing behind hull
        // traits (shipBonusAB…) — the trait rows already say it in English.
        // A curated few internal attrs ARE real player-facing effects
        // (max active drones, warp cap need) and get English labels here.
        const label = (attrHasDisplay.get(attrId) ?? false) ? what : INTERNAL_ATTR_LABELS[what];
        if (!label) continue;
        if (kind === 0 && fit.shipId === null) continue;
        if (fitAttrs) {
          // maxActiveDrones exists on the CHARACTER, never on fit items —
          // it matters exactly when the fit carries drones
          if (what === 'maxActiveDrones') {
            const hasDrones = fit.items.some(
              (i) => categoryOfGroup.get(groupOfType.get(i.typeId) ?? -1) === 18,
            );
            if (!hasDrones) continue;
          } else if (!fitAttrs.has(attrId)) {
            // the fit has NO such attribute — this skill moves nothing here
            continue;
          }
        }
        const e = touch(skillId);
        if (!e) continue;
        e.boosts.push(`${kind === 0 ? 'ship' : 'character'}: ${label}`);
      }
    }
  }

  return [...map.values()].sort(
    (a, b) =>
      a.tier - b.tier ||
      b.requiredLevel - a.requiredLevel ||
      a.skill.name.localeCompare(b.skill.name),
  );
}

// ---- topics ----

export interface Topic {
  id: string;
  label: string;
  groups?: string[];
  names?: string[];
  keywords?: string[];
}

/** curated topics — resolved against skill names/groups/descriptions at
 * runtime, so expansions adding skills are picked up on the next skilldb
 * rebuild without touching this list */
export const TOPICS: Topic[] = [
  { id: 'mining', label: 'Mining (ore)', keywords: ['mining', 'asteroid', 'mercoxit'], names: ['Astrogeology', 'Mining Barge', 'Exhumers', 'Expedition Frigates', 'Industrial Command Ships', 'Mining Director', 'Mining Foreman', 'Deep Core Mining'] },
  { id: 'gas', label: 'Gas huffing', keywords: ['gas cloud', 'gas harvest'], names: ['Gas Cloud Harvesting', 'Mining Frigate', 'Expedition Frigates'] },
  { id: 'ice', label: 'Ice harvesting', keywords: ['ice harvest'], names: ['Ice Harvesting', 'Mining Barge', 'Exhumers'] },
  { id: 'neut', label: 'Neuting / cap warfare', keywords: ['energy neutraliz', 'nosferatu', 'energy nosferatu', 'cap drain'], names: ['Capacitor Emission Systems'] },
  { id: 'capacitor', label: 'Capacitor', keywords: ['capacitor'], names: ['Capacitor Management', 'Capacitor Systems Operation', 'Controlled Bursts', 'Capacitor Emission Systems'] },
  { id: 'shield', label: 'Shield tank', groups: ['Shields'] },
  { id: 'armor', label: 'Armor tank', groups: ['Armor'] },
  { id: 'drones', label: 'Drones', groups: ['Drones'] },
  { id: 'missiles', label: 'Missiles', groups: ['Missiles'] },
  { id: 'gunnery', label: 'Gunnery', groups: ['Gunnery'] },
  { id: 'ewar', label: 'EWAR', groups: ['Electronic Systems'], keywords: ['jamming', 'sensor damp', 'target painter', 'tracking disrupt', 'guidance disrupt'] },
  { id: 'tackle', label: 'Tackle & propulsion', keywords: ['warp disrupt', 'warp scram', 'stasis web', 'propulsion jamming', 'interdiction'], names: ['Propulsion Jamming', 'Graviton Physics'] },
  { id: 'explo', label: 'Scanning & cloaking', groups: ['Scanning'], keywords: ['cloak', 'hacking', 'archaeology', 'astrometric', 'relic', 'data analyz'], names: ['Cloaking', 'Hacking', 'Archaeology', 'Astrometrics', 'Astrometric Acquisition', 'Astrometric Pinpointing', 'Astrometric Rangefinding'] },
  { id: 'navigation', label: 'Navigation & speed', groups: ['Navigation'] },
  { id: 'hauling', label: 'Hauling', keywords: ['industrial', 'freighter', 'transport ship', 'cargo'], names: ['Hull Upgrades'] },
  { id: 'reprocessing', label: 'Reprocessing', keywords: ['reprocess', 'refin', 'scrapmetal'] },
  { id: 'boosting', label: 'Fleet boosting', groups: ['Fleet Support'] },
  { id: 'trade', label: 'Trade & market', groups: ['Trade'] },
  { id: 'pi', label: 'Planetary industry', groups: ['Planet Management'], keywords: ['planet'] },
];

export interface TopicHit {
  skill: Skill;
  /** 0 = named explicitly, 1 = whole skill group, 2 = name keyword, 3 = description keyword */
  strength: number;
  reason: string;
}

/** skills matching a topic (or free-text keywords), strongest match first */
export function resolveTopic(topic: Topic | null, custom: string): TopicHit[] {
  const hits: TopicHit[] = [];
  const kw = custom.trim().toLowerCase()
    ? custom.trim().toLowerCase().split(/[,\s]+/).filter((w) => w.length >= 3)
    : [];
  for (const s of allSkills) {
    let best: TopicHit | null = null;
    const consider = (strength: number, reason: string) => {
      if (!best || strength < best.strength) best = { skill: s, strength, reason };
    };
    if (topic) {
      if (topic.names?.some((n) => n.toLowerCase() === s.name.toLowerCase())) consider(0, 'core skill for this topic');
      if (topic.groups?.includes(s.group)) consider(1, `${s.group} skill group`);
      for (const k of topic.keywords ?? []) {
        if (s.name.toLowerCase().includes(k)) consider(2, `name matches “${k}”`);
        else if (s.desc.toLowerCase().includes(k)) consider(3, `description mentions “${k}”`);
      }
    }
    for (const k of kw) {
      if (s.name.toLowerCase().includes(k)) consider(2, `name matches “${k}”`);
      else if (s.desc.toLowerCase().includes(k)) consider(3, `description mentions “${k}”`);
    }
    if (best) hits.push(best);
  }
  return hits.sort((a, b) => a.strength - b.strength || a.skill.name.localeCompare(b.skill.name));
}
