// Regenerate src/lib/piTypes.ts from the bundled CCP type table.
//
// Run after a `build:esfdata` refresh so a newly shipped planet type (or a
// new factory tier) is classified correctly instead of falling through as
// "not a PI structure" — which would make its contents invisible and, worse,
// leave its capacity out of the "how full is this planet" figure.
//
//   node scripts/build-pitypes.mjs
import fs from 'node:fs';
import path from 'node:path';
import protobuf from 'protobufjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const ESF = path.join(ROOT, 'src', 'data', 'esf');

/** inventory group -> the role that group plays on a planet */
const ROLE_BY_GROUP = {
  1027: 'command',    // Command Centers
  1028: 'factory',    // Processors
  1029: 'storage',    // Storage Facilities
  1030: 'launchpad',  // Spaceports
  1063: 'extractor',  // Extractor Control Units
};

const root = await protobuf.load(path.join(ESF, 'esf.proto'));
const Types = root.lookupType('Types');
const decoded = Types.toObject(Types.decode(fs.readFileSync(path.join(ESF, 'types.pb2'))), { longs: Number });
const types = decoded.entries ?? {};

const rows = [];
for (const [typeId, t] of Object.entries(types)) {
  const role = ROLE_BY_GROUP[t.groupID];
  if (role) rows.push({ typeId: Number(typeId), role, name: t.name });
}
rows.sort((a, b) => a.typeId - b.typeId);

const counts = {};
for (const r of rows) counts[r.role] = (counts[r.role] ?? 0) + 1;

const out = `// PI STRUCTURE TYPES -> their role on a planet.
//
// GENERATED by scripts/build-pitypes.mjs from the bundled CCP type table
// (groups ${Object.keys(ROLE_BY_GROUP).join(', ')}). It is a static table rather than a
// runtime lookup because typedb.json only carries an inventory group for
// SHIPS, and classifying a pin by name would break the moment CCP ships a
// new planet type.
//
// Public EVE data: nothing here is player-specific.

export type PinRole = 'command' | 'factory' | 'storage' | 'launchpad' | 'extractor';

const TABLE = new Map<number, PinRole>([
${rows.map((r) => `  [${r.typeId}, '${r.role}'],  // ${r.name}`).join('\n')}
]);

/** what this pin type does on a planet; null when it is not a PI structure */
export const pinRole = (typeId: number): PinRole | null => TABLE.get(typeId) ?? null;

/** roles whose capacity limits the planet — what "full" is measured against */
export const STORAGE_ROLES = new Set<PinRole>(['command', 'storage', 'launchpad']);

export const PI_TYPE_COUNT = TABLE.size;
`;

fs.writeFileSync(path.join(ROOT, 'src', 'lib', 'piTypes.ts'), out);
console.log(`wrote src/lib/piTypes.ts — ${rows.length} types`, counts);
