// GENERATED by `npm run build:esfproto` (scripts/build-esfproto.mjs → protobufjs-cli pbjs, static-module)
// from esf.proto — DO NOT EDIT; regenerate when esf.proto changes. Static decoders, not reflection,
// because reflection compiles its decoders from source text at runtime and the Content-Security-Policy
// refuses that (v0.224.1). tests/esfstatic.test.cjs proves equality with the reflection decode.
import * as $protobuf from "protobufjs";
/** Namespace esf. */
export namespace esf {

    /** Properties of a TypeDogma. */
    interface ITypeDogma {

        /** TypeDogma entries */
        entries?: ({ [k: string]: esf.TypeDogma.ITypeDogmaEntry }|null);
    }

    /** Represents a TypeDogma. */
    class TypeDogma implements ITypeDogma {

        /**
         * Constructs a new TypeDogma.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.ITypeDogma);

        /** TypeDogma entries. */
        public entries: { [k: string]: esf.TypeDogma.ITypeDogmaEntry };

        /**
         * Decodes a TypeDogma message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns TypeDogma
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.TypeDogma;

        /**
         * Gets the default type url for TypeDogma
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace TypeDogma {

        /** Properties of a TypeDogmaEntry. */
        interface ITypeDogmaEntry {

            /** TypeDogmaEntry dogmaAttributes */
            dogmaAttributes?: (esf.TypeDogma.TypeDogmaEntry.IDogmaAttributes[]|null);

            /** TypeDogmaEntry dogmaEffects */
            dogmaEffects?: (esf.TypeDogma.TypeDogmaEntry.IDogmaEffects[]|null);
        }

        /** Represents a TypeDogmaEntry. */
        class TypeDogmaEntry implements ITypeDogmaEntry {

            /**
             * Constructs a new TypeDogmaEntry.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.TypeDogma.ITypeDogmaEntry);

            /** TypeDogmaEntry dogmaAttributes. */
            public dogmaAttributes: esf.TypeDogma.TypeDogmaEntry.IDogmaAttributes[];

            /** TypeDogmaEntry dogmaEffects. */
            public dogmaEffects: esf.TypeDogma.TypeDogmaEntry.IDogmaEffects[];

            /**
             * Decodes a TypeDogmaEntry message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns TypeDogmaEntry
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.TypeDogma.TypeDogmaEntry;

            /**
             * Gets the default type url for TypeDogmaEntry
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }

        namespace TypeDogmaEntry {

            /** Properties of a DogmaAttributes. */
            interface IDogmaAttributes {

                /** DogmaAttributes attributeID */
                attributeID: number;

                /** DogmaAttributes value */
                value: number;
            }

            /** Represents a DogmaAttributes. */
            class DogmaAttributes implements IDogmaAttributes {

                /**
                 * Constructs a new DogmaAttributes.
                 * @param [properties] Properties to set
                 */
                constructor(properties?: esf.TypeDogma.TypeDogmaEntry.IDogmaAttributes);

                /** DogmaAttributes attributeID. */
                public attributeID: number;

                /** DogmaAttributes value. */
                public value: number;

                /**
                 * Decodes a DogmaAttributes message from the specified reader or buffer.
                 * @param reader Reader or buffer to decode from
                 * @param [length] Message length if known beforehand
                 * @returns DogmaAttributes
                 * @throws {Error} If the payload is not a reader or valid buffer
                 * @throws {$protobuf.util.ProtocolError} If required fields are missing
                 */
                public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.TypeDogma.TypeDogmaEntry.DogmaAttributes;

                /**
                 * Gets the default type url for DogmaAttributes
                 * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
                 * @returns The default type url
                 */
                public static getTypeUrl(typeUrlPrefix?: string): string;
            }

            /** Properties of a DogmaEffects. */
            interface IDogmaEffects {

                /** DogmaEffects effectID */
                effectID: number;

                /** DogmaEffects isDefault */
                isDefault: boolean;
            }

            /** Represents a DogmaEffects. */
            class DogmaEffects implements IDogmaEffects {

                /**
                 * Constructs a new DogmaEffects.
                 * @param [properties] Properties to set
                 */
                constructor(properties?: esf.TypeDogma.TypeDogmaEntry.IDogmaEffects);

                /** DogmaEffects effectID. */
                public effectID: number;

                /** DogmaEffects isDefault. */
                public isDefault: boolean;

                /**
                 * Decodes a DogmaEffects message from the specified reader or buffer.
                 * @param reader Reader or buffer to decode from
                 * @param [length] Message length if known beforehand
                 * @returns DogmaEffects
                 * @throws {Error} If the payload is not a reader or valid buffer
                 * @throws {$protobuf.util.ProtocolError} If required fields are missing
                 */
                public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.TypeDogma.TypeDogmaEntry.DogmaEffects;

                /**
                 * Gets the default type url for DogmaEffects
                 * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
                 * @returns The default type url
                 */
                public static getTypeUrl(typeUrlPrefix?: string): string;
            }
        }
    }

    /** Properties of a Types. */
    interface ITypes {

        /** Types entries */
        entries?: ({ [k: string]: esf.Types.IType }|null);
    }

    /** Represents a Types. */
    class Types implements ITypes {

        /**
         * Constructs a new Types.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.ITypes);

        /** Types entries. */
        public entries: { [k: string]: esf.Types.IType };

        /**
         * Decodes a Types message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns Types
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.Types;

        /**
         * Gets the default type url for Types
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace Types {

        /** Properties of a Type. */
        interface IType {

            /** Type name */
            name: string;

            /** Type groupID */
            groupID: number;

            /** Type categoryID */
            categoryID: number;

            /** Type published */
            published: boolean;

            /** Type factionID */
            factionID?: (number|null);

            /** Type marketGroupID */
            marketGroupID?: (number|null);

            /** Type metaGroupID */
            metaGroupID?: (number|null);

            /** Type capacity */
            capacity?: (number|null);

            /** Type mass */
            mass?: (number|null);

            /** Type radius */
            radius?: (number|null);

            /** Type volume */
            volume?: (number|null);
        }

        /** Represents a Type. */
        class Type implements IType {

            /**
             * Constructs a new Type.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.Types.IType);

            /** Type name. */
            public name: string;

            /** Type groupID. */
            public groupID: number;

            /** Type categoryID. */
            public categoryID: number;

            /** Type published. */
            public published: boolean;

            /** Type factionID. */
            public factionID: number;

            /** Type marketGroupID. */
            public marketGroupID: number;

            /** Type metaGroupID. */
            public metaGroupID: number;

            /** Type capacity. */
            public capacity: number;

            /** Type mass. */
            public mass: number;

            /** Type radius. */
            public radius: number;

            /** Type volume. */
            public volume: number;

            /**
             * Decodes a Type message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns Type
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.Types.Type;

            /**
             * Gets the default type url for Type
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }
    }

    /** Properties of a Categories. */
    interface ICategories {

        /** Categories entries */
        entries?: ({ [k: string]: esf.Categories.ICategory }|null);
    }

    /** Represents a Categories. */
    class Categories implements ICategories {

        /**
         * Constructs a new Categories.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.ICategories);

        /** Categories entries. */
        public entries: { [k: string]: esf.Categories.ICategory };

        /**
         * Decodes a Categories message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns Categories
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.Categories;

        /**
         * Gets the default type url for Categories
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace Categories {

        /** Properties of a Category. */
        interface ICategory {

            /** Category name */
            name: string;

            /** Category published */
            published: boolean;
        }

        /** Represents a Category. */
        class Category implements ICategory {

            /**
             * Constructs a new Category.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.Categories.ICategory);

            /** Category name. */
            public name: string;

            /** Category published. */
            public published: boolean;

            /**
             * Decodes a Category message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns Category
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.Categories.Category;

            /**
             * Gets the default type url for Category
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }
    }

    /** Properties of a Groups. */
    interface IGroups {

        /** Groups entries */
        entries?: ({ [k: string]: esf.Groups.IGroup }|null);
    }

    /** Represents a Groups. */
    class Groups implements IGroups {

        /**
         * Constructs a new Groups.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.IGroups);

        /** Groups entries. */
        public entries: { [k: string]: esf.Groups.IGroup };

        /**
         * Decodes a Groups message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns Groups
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.Groups;

        /**
         * Gets the default type url for Groups
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace Groups {

        /** Properties of a Group. */
        interface IGroup {

            /** Group name */
            name: string;

            /** Group categoryID */
            categoryID: number;

            /** Group published */
            published: boolean;
        }

        /** Represents a Group. */
        class Group implements IGroup {

            /**
             * Constructs a new Group.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.Groups.IGroup);

            /** Group name. */
            public name: string;

            /** Group categoryID. */
            public categoryID: number;

            /** Group published. */
            public published: boolean;

            /**
             * Decodes a Group message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns Group
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.Groups.Group;

            /**
             * Gets the default type url for Group
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }
    }

    /** Properties of a MarketGroups. */
    interface IMarketGroups {

        /** MarketGroups entries */
        entries?: ({ [k: string]: esf.MarketGroups.IMarketGroup }|null);
    }

    /** Represents a MarketGroups. */
    class MarketGroups implements IMarketGroups {

        /**
         * Constructs a new MarketGroups.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.IMarketGroups);

        /** MarketGroups entries. */
        public entries: { [k: string]: esf.MarketGroups.IMarketGroup };

        /**
         * Decodes a MarketGroups message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns MarketGroups
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.MarketGroups;

        /**
         * Gets the default type url for MarketGroups
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace MarketGroups {

        /** Properties of a MarketGroup. */
        interface IMarketGroup {

            /** MarketGroup name */
            name: string;

            /** MarketGroup parentGroupID */
            parentGroupID?: (number|null);

            /** MarketGroup iconID */
            iconID?: (number|null);
        }

        /** Represents a MarketGroup. */
        class MarketGroup implements IMarketGroup {

            /**
             * Constructs a new MarketGroup.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.MarketGroups.IMarketGroup);

            /** MarketGroup name. */
            public name: string;

            /** MarketGroup parentGroupID. */
            public parentGroupID: number;

            /** MarketGroup iconID. */
            public iconID: number;

            /**
             * Decodes a MarketGroup message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns MarketGroup
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.MarketGroups.MarketGroup;

            /**
             * Gets the default type url for MarketGroup
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }
    }

    /** Properties of a DogmaAttributes. */
    interface IDogmaAttributes {

        /** DogmaAttributes entries */
        entries?: ({ [k: string]: esf.DogmaAttributes.IDogmaAttribute }|null);
    }

    /** Represents a DogmaAttributes. */
    class DogmaAttributes implements IDogmaAttributes {

        /**
         * Constructs a new DogmaAttributes.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.IDogmaAttributes);

        /** DogmaAttributes entries. */
        public entries: { [k: string]: esf.DogmaAttributes.IDogmaAttribute };

        /**
         * Decodes a DogmaAttributes message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns DogmaAttributes
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.DogmaAttributes;

        /**
         * Gets the default type url for DogmaAttributes
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace DogmaAttributes {

        /** Properties of a DogmaAttribute. */
        interface IDogmaAttribute {

            /** DogmaAttribute name */
            name: string;

            /** DogmaAttribute published */
            published: boolean;

            /** DogmaAttribute defaultValue */
            defaultValue: number;

            /** DogmaAttribute highIsGood */
            highIsGood: boolean;

            /** DogmaAttribute stackable */
            stackable: boolean;
        }

        /** Represents a DogmaAttribute. */
        class DogmaAttribute implements IDogmaAttribute {

            /**
             * Constructs a new DogmaAttribute.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.DogmaAttributes.IDogmaAttribute);

            /** DogmaAttribute name. */
            public name: string;

            /** DogmaAttribute published. */
            public published: boolean;

            /** DogmaAttribute defaultValue. */
            public defaultValue: number;

            /** DogmaAttribute highIsGood. */
            public highIsGood: boolean;

            /** DogmaAttribute stackable. */
            public stackable: boolean;

            /**
             * Decodes a DogmaAttribute message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns DogmaAttribute
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.DogmaAttributes.DogmaAttribute;

            /**
             * Gets the default type url for DogmaAttribute
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }
    }

    /** Properties of a DogmaEffects. */
    interface IDogmaEffects {

        /** DogmaEffects entries */
        entries?: ({ [k: string]: esf.DogmaEffects.IDogmaEffect }|null);
    }

    /** Represents a DogmaEffects. */
    class DogmaEffects implements IDogmaEffects {

        /**
         * Constructs a new DogmaEffects.
         * @param [properties] Properties to set
         */
        constructor(properties?: esf.IDogmaEffects);

        /** DogmaEffects entries. */
        public entries: { [k: string]: esf.DogmaEffects.IDogmaEffect };

        /**
         * Decodes a DogmaEffects message from the specified reader or buffer.
         * @param reader Reader or buffer to decode from
         * @param [length] Message length if known beforehand
         * @returns DogmaEffects
         * @throws {Error} If the payload is not a reader or valid buffer
         * @throws {$protobuf.util.ProtocolError} If required fields are missing
         */
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.DogmaEffects;

        /**
         * Gets the default type url for DogmaEffects
         * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
         * @returns The default type url
         */
        public static getTypeUrl(typeUrlPrefix?: string): string;
    }

    namespace DogmaEffects {

        /** Properties of a DogmaEffect. */
        interface IDogmaEffect {

            /** DogmaEffect name */
            name: string;

            /** DogmaEffect effectCategory */
            effectCategory: number;

            /** DogmaEffect electronicChance */
            electronicChance: boolean;

            /** DogmaEffect isAssistance */
            isAssistance: boolean;

            /** DogmaEffect isOffensive */
            isOffensive: boolean;

            /** DogmaEffect isWarpSafe */
            isWarpSafe: boolean;

            /** DogmaEffect propulsionChance */
            propulsionChance: boolean;

            /** DogmaEffect rangeChance */
            rangeChance: boolean;

            /** DogmaEffect dischargeAttributeID */
            dischargeAttributeID?: (number|null);

            /** DogmaEffect durationAttributeID */
            durationAttributeID?: (number|null);

            /** DogmaEffect rangeAttributeID */
            rangeAttributeID?: (number|null);

            /** DogmaEffect falloffAttributeID */
            falloffAttributeID?: (number|null);

            /** DogmaEffect trackingSpeedAttributeID */
            trackingSpeedAttributeID?: (number|null);

            /** DogmaEffect fittingUsageChanceAttributeID */
            fittingUsageChanceAttributeID?: (number|null);

            /** DogmaEffect resistanceAttributeID */
            resistanceAttributeID?: (number|null);

            /** DogmaEffect modifierInfo */
            modifierInfo?: (esf.DogmaEffects.DogmaEffect.IModifierInfo[]|null);
        }

        /** Represents a DogmaEffect. */
        class DogmaEffect implements IDogmaEffect {

            /**
             * Constructs a new DogmaEffect.
             * @param [properties] Properties to set
             */
            constructor(properties?: esf.DogmaEffects.IDogmaEffect);

            /** DogmaEffect name. */
            public name: string;

            /** DogmaEffect effectCategory. */
            public effectCategory: number;

            /** DogmaEffect electronicChance. */
            public electronicChance: boolean;

            /** DogmaEffect isAssistance. */
            public isAssistance: boolean;

            /** DogmaEffect isOffensive. */
            public isOffensive: boolean;

            /** DogmaEffect isWarpSafe. */
            public isWarpSafe: boolean;

            /** DogmaEffect propulsionChance. */
            public propulsionChance: boolean;

            /** DogmaEffect rangeChance. */
            public rangeChance: boolean;

            /** DogmaEffect dischargeAttributeID. */
            public dischargeAttributeID: number;

            /** DogmaEffect durationAttributeID. */
            public durationAttributeID: number;

            /** DogmaEffect rangeAttributeID. */
            public rangeAttributeID: number;

            /** DogmaEffect falloffAttributeID. */
            public falloffAttributeID: number;

            /** DogmaEffect trackingSpeedAttributeID. */
            public trackingSpeedAttributeID: number;

            /** DogmaEffect fittingUsageChanceAttributeID. */
            public fittingUsageChanceAttributeID: number;

            /** DogmaEffect resistanceAttributeID. */
            public resistanceAttributeID: number;

            /** DogmaEffect modifierInfo. */
            public modifierInfo: esf.DogmaEffects.DogmaEffect.IModifierInfo[];

            /**
             * Decodes a DogmaEffect message from the specified reader or buffer.
             * @param reader Reader or buffer to decode from
             * @param [length] Message length if known beforehand
             * @returns DogmaEffect
             * @throws {Error} If the payload is not a reader or valid buffer
             * @throws {$protobuf.util.ProtocolError} If required fields are missing
             */
            public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.DogmaEffects.DogmaEffect;

            /**
             * Gets the default type url for DogmaEffect
             * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
             * @returns The default type url
             */
            public static getTypeUrl(typeUrlPrefix?: string): string;
        }

        namespace DogmaEffect {

            /** Properties of a ModifierInfo. */
            interface IModifierInfo {

                /** ModifierInfo domain */
                domain: esf.DogmaEffects.DogmaEffect.ModifierInfo.Domain;

                /** ModifierInfo func */
                func: esf.DogmaEffects.DogmaEffect.ModifierInfo.Func;

                /** ModifierInfo modifiedAttributeID */
                modifiedAttributeID?: (number|null);

                /** ModifierInfo modifyingAttributeID */
                modifyingAttributeID?: (number|null);

                /** ModifierInfo operation */
                operation?: (number|null);

                /** ModifierInfo groupID */
                groupID?: (number|null);

                /** ModifierInfo skillTypeID */
                skillTypeID?: (number|null);
            }

            /** Represents a ModifierInfo. */
            class ModifierInfo implements IModifierInfo {

                /**
                 * Constructs a new ModifierInfo.
                 * @param [properties] Properties to set
                 */
                constructor(properties?: esf.DogmaEffects.DogmaEffect.IModifierInfo);

                /** ModifierInfo domain. */
                public domain: esf.DogmaEffects.DogmaEffect.ModifierInfo.Domain;

                /** ModifierInfo func. */
                public func: esf.DogmaEffects.DogmaEffect.ModifierInfo.Func;

                /** ModifierInfo modifiedAttributeID. */
                public modifiedAttributeID: number;

                /** ModifierInfo modifyingAttributeID. */
                public modifyingAttributeID: number;

                /** ModifierInfo operation. */
                public operation: number;

                /** ModifierInfo groupID. */
                public groupID: number;

                /** ModifierInfo skillTypeID. */
                public skillTypeID: number;

                /**
                 * Decodes a ModifierInfo message from the specified reader or buffer.
                 * @param reader Reader or buffer to decode from
                 * @param [length] Message length if known beforehand
                 * @returns ModifierInfo
                 * @throws {Error} If the payload is not a reader or valid buffer
                 * @throws {$protobuf.util.ProtocolError} If required fields are missing
                 */
                public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): esf.DogmaEffects.DogmaEffect.ModifierInfo;

                /**
                 * Gets the default type url for ModifierInfo
                 * @param [typeUrlPrefix] your custom typeUrlPrefix(default "type.googleapis.com")
                 * @returns The default type url
                 */
                public static getTypeUrl(typeUrlPrefix?: string): string;
            }

            namespace ModifierInfo {

                /** Domain enum. */
                enum Domain {
                    itemID = 0,
                    shipID = 1,
                    charID = 2,
                    otherID = 3,
                    structureID = 4,
                    target = 5,
                    targetID = 6
                }

                /** Func enum. */
                enum Func {
                    ItemModifier = 0,
                    LocationGroupModifier = 1,
                    LocationModifier = 2,
                    LocationRequiredSkillModifier = 3,
                    OwnerRequiredSkillModifier = 4,
                    EffectStopper = 5
                }
            }
        }
    }
}
